#ifndef __IOX_ERROR_H__
#define ERR_PARSE_ARGS "Error in parsing args data"
#define ERR_NO_UNIT_ID "No unid Provided"
#define ERR_DEVICE_CREATE "Device already created"
#define ERR_INVALID_PROVISION "Invalid provision value"
#define ERR_WRONG_CONFIG_LEVEL "Wrong configuration for level output"
#define ERR_WRONG_CONFIG_FREQ "Wrong configuration for Frequency output"
#define ERR_WRONG_CONFIG_PULSE "Wrong configuration for Pulse output"
#define ERR_WRONG_CONFIG_PWM_FREQ "Wrong configuration for PWM Frequency output"
#define ERR_WRONG_CONFIG_PWM_DUTY "Wrong configuration for PWM Duty-cycle output"
#define ERR_PARSE_JSON "Error in parsing json object"
#define ERR_PARSE_DO_PORT "rror in parsing do port"
#define ERR_INVALID_PORT "The port asked for is not valid"
#define ERR_PARSE_RELAY_PORT "Error in parsing relay port"
#define ERR_PARSE_DIGITAL_IO "Error while parsin Digital Input"
#define ERR_PARSE_MESSAGE "Error in parsing message data"
#define ERR_INVALID_UNIT_ID "Invalid unid string"
#define ERR_INCORRECT_DEVICE_TYPE "Incorrect device type"
#define ERR_NO_DEVICE_TYPE "No device type provided"
#define ERR_NO_UNPROVISIONED_STATE "Device not in UNPROVISIONED state"
#define ERR_NO_SYS_DEVICE_DEL "SYS Device can not be deleted"
#define ERR_NO_DIO_DEVICE_DEL "Built-in DIO Device can not be deleted"
#define ERR_IOX_TEST_HANDLE "ERROR in iox_test handle"
#define ERR_UNSUPPORTED_OP_SYS "Unsupported operations for SYS device"
#define ERR_IOX_WINK_HANDLE "ERROR in iox_wink handle"
#define ERR_IOX_LOAD_HANDLE "ERROR in iox_load handle"
#define ERR_IOX_MSG_HANDLE "ERROR in iox_message handle"
#define ERR_IOX_REPAIR_HANDLE "ERROR in iox_repair handle"
#define ERR_IOX_REPLACE_HANDLE "ERROR in iox_replace handle"
#define ERR_IOX_RESET_HANDLE "ERROR in iox_reset handle"
#define ERR_INVALID_RELAY_VAL "Invalid Value for relay"
#define ERR_NO_LEVEL_ITEM "No level Item present"
#endif /*__IOX_ERROR_H__*/
